import { LandingConfig } from "./types";

export const defaultConfig: LandingConfig = {
  brand: {
    logo: "/images/logo.png",
    name: "REDILL 공식스토어",
  },
  header: {
    title: "2년 연속 1위, 누적 8관왕 기념",
    badgeText1: "국내최초·국내유일",
    badgeText2: "타격감 특허, 맛 극대화 특허",
    bgColor: "#1a1a1a",
    badgeBg: "transparent",
    badgeBorderColor: "#e63030",
    badgeTextColor1: "#e63030",
    badgeTextColor2: "#ffffff",
  },
  event: {
    label: "EVENT",
    labelBg: "#dc2626",
    labelColor: "#ffffff",
    deadline: "기한: 03월17일(화) 오후5시 마감",
    deadlineBg: "#fee2e2",
    deadlineColor: "#991b1b",
    products: [
      {
        id: 1,
        name: "3+1 골라담기",
        nameColor: "#111827",
        nameSize: "14px",
        badge: "BEST",
        showBadge: true,
        thumbnail: "/images/product1.jpg",
        discount: "57% 할인  3개사면 1개 무료!!",
        discountColor: "#ef4444",
        discountSize: "12px",
        originalPrice: "26,000원",
        originalPriceColor: "#9ca3af",
        originalPriceSize: "12px",
        salePrice: "11,175원",
        salePriceColor: "#111827",
        salePriceSize: "14px",
        link: "https://example.com/product1",
        featured: true,
        gradientIndex: 0,
      },
      {
        id: 2,
        name: "2+1 골라담기",
        nameColor: "#111827",
        nameSize: "14px",
        badge: "HOT",
        showBadge: true,
        thumbnail: "/images/product2.jpg",
        discount: "50% 할인  2개사면 1개 무료!!",
        discountColor: "#ef4444",
        discountSize: "12px",
        originalPrice: "18,000원",
        originalPriceColor: "#9ca3af",
        originalPriceSize: "12px",
        salePrice: "8,900원",
        salePriceColor: "#111827",
        salePriceSize: "14px",
        link: "https://example.com/product2",
        featured: false,
        gradientIndex: 1,
      },
    ],
  },
  services: {
    label: "SERVICE & BRAND",
    items: [
      {
        id: 1,
        icon: "/images/icon1.png",
        name: "안전 시험성적서",
        badge: "국내 최다보유",
        badgeBg: "#dcfce7",
        badgeColor: "#15803d",
        description: "안심하고 즐기세요!",
      },
      {
        id: 2,
        icon: "",
        name: "빠른 배송",
        badge: "당일발송",
        badgeBg: "#dbeafe",
        badgeColor: "#1d4ed8",
        description: "오후 2시 이전 주문 시 당일 발송",
      },
    ],
  },
  footer: {
    awards: "고객 만족도 1위 | 재구매율 1위",
    copyright: "© 2025 REDILL Corp.",
    disclaimer:
      "※ 본 이벤트는 한정 수량으로 진행되며, 재고 소진 시 예고 없이 조기 종료될 수 있습니다.",
  },
  seo: {
    title: "콩즈 라이프스타일 스토어",
    description: "당신의 일상에 특별한 경험을 더합니다",
    ogTitle: "콩즈 라이프스타일 스토어",
    ogDescription: "당신의 일상에 특별한 경험을 더합니다",
    ogImage: "",
    ogUrl: "",
  },
};
