import { LandingConfig } from "./types";

export const defaultConfig: LandingConfig = {
  brand: {
    logo: "https://rmuerveslfcdaqpdxggl.supabase.co/storage/v1/object/public/landing-images/1773812066335-vplw62.png",
    name: "KONGZJUICE 공식스토어",
  },
  header: {
    title: "콩즈쥬스 누적 판매량 100만 기념",
    badgeText1: "국내 유일",
    badgeText2: "자체 개발 레시피로 3배 진한 맛표현",
    bgColor: "#1a1a1a",
    badgeBg: "#e01883",
    badgeBorderColor: "#e01883",
    badgeTextColor1: "#ffffff",
    badgeTextColor2: "#ffffff",
  },
  event: {
    label: "EVENT",
    labelBg: "#e01883",
    labelColor: "#ffffff",
    deadline: "기한: 03월19일(목) 오후5시 마감",
    deadlineBg: "#f2f2f2",
    deadlineColor: "#000000",
    products: [
      {
        id: 1,
        name: "콩즈쥬스 24% 할인",
        nameColor: "#111827",
        nameSize: "16px",
        badge: "BEST",
        showBadge: true,
        thumbnail: "https://rmuerveslfcdaqpdxggl.supabase.co/storage/v1/object/public/landing-images/1773814027782-mo53un.png",
        discount: "광고 전용 최저가 링크!!",
        discountColor: "#e01883",
        discountSize: "14px",
        originalPrice: "35,000",
        originalPriceColor: "#9ca3af",
        originalPriceSize: "12px",
        salePrice: "26,600",
        salePriceColor: "#111827",
        salePriceSize: "16px",
        link: "https://example.com/product1",
        featured: true,
        gradientIndex: 1,
        showArrow: true,
      },
      {
        id: 2,
        name: "신규 회원 전용",
        nameColor: "#111827",
        nameSize: "16px",
        badge: "",
        showBadge: true,
        thumbnail: "https://rmuerveslfcdaqpdxggl.supabase.co/storage/v1/object/public/landing-images/1773815752029-duxu2v.png",
        discount: "SMS 수신 동의시 4만원 이상의 쿠폰팩 지급!!",
        discountColor: "#e01883",
        discountSize: "14px",
        originalPrice: "",
        originalPriceColor: "#9ca3af",
        originalPriceSize: "12px",
        salePrice: "",
        salePriceColor: "#111827",
        salePriceSize: "16px",
        link: "",
        featured: false,
        gradientIndex: 0,
        showArrow: true,
      },
    ],
  },
  services: {
    label: "SERVICE & BRAND",
    items: [
      {
        id: 1,
        icon: "https://rmuerveslfcdaqpdxggl.supabase.co/storage/v1/object/public/landing-images/1773815049472-7d9uv8.png",
        name: "안전 시험성적서",
        badge: "LOT별 관리",
        badgeBg: "#dcfce7",
        badgeColor: "#15803d",
        description: "안심하고 즐기세요!",
      },
      {
        id: 2,
        icon: "https://rmuerveslfcdaqpdxggl.supabase.co/storage/v1/object/public/landing-images/1773815052047-zlugvo.png",
        name: "빠른 배송",
        badge: "주말 발송",
        badgeBg: "#dbeafe",
        badgeColor: "#1d4ed8",
        description: "오후 3시 이전 주문 시 당일 발송",
      },
    ],
  },
  footer: {
    awards: "국내 1위 | 재구매율 70% UP",
    copyright: "※ 본 이벤트는 한정 수량으로 진행되며, 재고 소진 시 예고 없이 조기 종료될 수 있습니다.",
    disclaimer: "© Design by KongzJuice",
  },
  seo: {
    title: "콩즈쥬스",
    description: "당신의 일상에 특별한 경험을 더합니다",
    ogTitle: "콩즈쥬스 공식 스토어",
    ogDescription: "당신의 일상에 특별한 경험을 더합니다",
    ogImage: "",
    ogUrl: "",
  },
};
